### ISSUE TITLE
HTTP to HTTPS

### ISSUE THREAD

**Issue by christianswanepoel** [WP-Plus/Smart-Slider-3-REST-API#4]
I have changed a site url from HTTP to HTTPs. Image URLs aren't HTTPs on existing pages, but correctly shows HTTPs on new pages.

I have followed the steps outlined here without any success - https://smartslider3.helpscoutdocs.com/article/1311-moving-from-http-to-https

I am on the latest versions of Wordpress and SmartSlider 3.

Looking for a possible workaround.

**Comment by zoliszabo** [comment]
Hi @christianswanepoel, sorry for the late reply. Hopefully, your issue was already resolved. In any case, it is not related to this plugin and most probably it is not strictly related to SmartSlider either, but WordPress in general. Online tutorials may help you to correctly migrate your WordPress instance from http to https, for example this one: https://www.wpbeginner.com/wp-tutorials/how-to-add-ssl-and-https-in-wordpress/.
